#  Rules: https://realm.github.io/SwiftLint/rule-directory.html

disabled_rules:
    - trailing_whitespace
    - no_extension_access_modifier

opt_in_rules:
    - anyobject_protocol
    - array_init
    - attributes
    # - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    # - conditional_returns_on_newline
    - contains_over_first_not_nil
    - contains_over_filter_is_empty
    - contains_over_range_nil_comparison
    - contains_over_filter_count
    - convenience_type
    # - discouraged_object_literal
    # - discouraged_optional_boolean
    # - discouraged_optional_collection
    - empty_count
    - empty_string
    - empty_xctest_method
    # - explicit_acl
    # - explicit_enum_raw_value
    # - explicit_init
    - explicit_self
    # - explicit_top_level_acl
    # - explicit_type_interface
    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    # - file_header
    # - file_name
    - first_where
    - force_unwrapping
    # - function_default_parameter_at_end
    - identical_operands
    - implicit_return
    # - implicitly_unwrapped_optional
    - joined_default_parameter
    - legacy_random
    # - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - missing_docs
    # - modifier_order
    # - multiline_arguments
    # - multiline_function_chains
    - multiline_parameters
    - multiline_parameters_brackets
    - nimble_operator
    - no_extension_access_modifier
    - no_grouping_extension
    # - number_separator
    # - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    # - pattern_matching_keywords
    - prefixed_toplevel_constant
    - private_action
    - private_outlet
    - prohibited_interface_builder
    - prohibited_super_call
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - redundant_nil_coalescing
    - redundant_type_annotation
    - required_enum_case
    - single_test_class
    - sorted_first_last
    # - sorted_imports
    # - static_operator
    # - strict_fileprivate
    # - switch_case_on_newline
    - toggle_bool
    # - trailing_closure
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    # - untyped_error_in_catch
    - unused_import
    - yoda_condition

excluded:
    - Carthage
    - fastlane
    - builds
    - Obfuscation.playground

function_parameter_count:
    warning: 5
    error: 8

line_length:
    warning: 125
    error: 200

file_length:
    - 500
    - 1300

function_body_length:
    - 100 # warning
    - 200 # error

type_body_length:
    - 300 # warning
    - 400 # error

type_name:
    min_length:
        warning: 1
        error: 0
    max_length:
        warning: 60
        error: 80
    excluded:

identifier_name:
    min_length:
        warning: 1
        error: 0
    max_length:
        warning: 60
        error: 80
    excluded:
        - vc
        - to
        - x
        - y
        - _work
        - KiPoiStandardCategoryNone

force_cast: error
force_try: error
force_unwrapping: error

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

# Sources for custom rules: https://github.com/brandenr/swiftlintconfig, https://github.com/IBM-Swift/Package-Builder
custom_rules:
    comments_space:
        name: "Space After Comment"
        regex: "(^ */{2,3}\\w+)"
        message: "There should be a space after // or ///"
        severity: warning
    multiple_empty_lines:
        name: "Multiple Empty Lines"
        regex: "((?:\\s*\n){3,})"
        message: "There are too many line breaks"
        severity: warning
    force_https:
        name: "Force HTTPS over HTTP"
        regex: "((?i)http(?!s))"
        match_kinds: string
        message: "HTTPS should be favored over HTTP"
        severity: warning
    double_space:
        include: "*.swift"
        name: "Double space"
        regex: "([a-z,A-Z] \\s+)"
        message: "Double space between keywords"
        match_kinds: keyword
        severity: warning
